FROM docker.io/library/node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Expose the Angular dev server port
EXPOSE 4200

# Run ng serve and allow external connections
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]